### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by tad-swift** [RRethy/ToonUp#12]
I am trying to use the app but I can't seem to play any of the videos. All of them are stuck on a black loading screen.

**Comment by RRethy** [comment]
API seems to be broken. The API that is being used is the same as the API for [this app](http://www.mobi24.net/toon.html). I haven't had time recently, but the fix would be to use Charles proxy to monitor the network calls from it, get the new network call used playing videos, then swap that into the retrofit service. Not sure when (or if) I'll get around to that.

**Comment by ToniNgethe** [comment]
Hey, what api are you using to stream the movies on exoplayer2?
